-- PAINEL PRODUCAO - Supabase schema (Auth + RBAC + pedidos)

create extension if not exists "uuid-ossp";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('admin', 'operador');
  end if;
end $$;

alter type public.user_role add value if not exists 'visualizador';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'visualizador',
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.profiles
  alter column role set default 'visualizador';

create or replace function public.handle_new_profile_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  resolved_name text;
begin
  resolved_name := coalesce(
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'display_name', '')), ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    'Usuario'
  );

  insert into public.profiles (id, role, display_name, active)
  values (new.id, 'visualizador', resolved_name, false)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_profile_from_auth();

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  data_producao text not null,
  mes text,
  operador text not null,
  status text not null,
  order_id text not null,
  prefixo text not null,
  codigo text not null,
  nome_cliente text not null,
  tamanho_cm text,
  tipo_caixa text not null,
  peca_unica boolean not null default false,
  maquina_impressao text,
  qtd_imagens integer not null default 1,
  chapas_impressas integer not null default 0,
  caixas_produzidas integer not null default 0,
  area_mq numeric not null default 0,
  c_ml numeric not null default 0,
  m_ml numeric not null default 0,
  y_ml numeric not null default 0,
  k_ml numeric not null default 0,
  tinta_total numeric not null default 0,
  custo_tinta numeric not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint pedidos_unq_data_operador_order unique (data_producao, operador, order_id)
);

alter table public.pedidos add column if not exists mes text;
update public.pedidos
set mes = substring(data_producao from 7 for 4) || '-' || substring(data_producao from 4 for 2)
where (mes is null or mes = '')
  and data_producao ~ '^\d{2}/\d{2}/\d{4}$';

create index if not exists pedidos_data_idx on public.pedidos (data_producao);
create index if not exists pedidos_mes_idx on public.pedidos (mes);
create index if not exists pedidos_operador_idx on public.pedidos (operador);
create index if not exists pedidos_status_idx on public.pedidos (status);
create index if not exists pedidos_codigo_idx on public.pedidos (codigo);

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = uid
      and active = true
      and role = 'admin'
  );
$$;

create or replace function public.is_active_user(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = uid
      and active = true
  );
$$;

create or replace function public.can_import(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = uid
      and active = true
      and role in ('admin', 'operador')
  );
$$;

alter table public.profiles enable row level security;
alter table public.pedidos enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists "profiles_admin_manage" on public.profiles;
create policy "profiles_admin_manage"
on public.profiles
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "pedidos_select_active_users" on public.pedidos;
create policy "pedidos_select_active_users"
on public.pedidos
for select
to authenticated
using (public.is_active_user(auth.uid()));

drop policy if exists "pedidos_insert_active_users" on public.pedidos;
create policy "pedidos_insert_active_users"
on public.pedidos
for insert
to authenticated
with check (
  public.can_import(auth.uid())
  and (created_by is null or created_by = auth.uid())
);

drop policy if exists "pedidos_update_admin" on public.pedidos;
create policy "pedidos_update_admin"
on public.pedidos
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "pedidos_delete_admin" on public.pedidos;
create policy "pedidos_delete_admin"
on public.pedidos
for delete
to authenticated
using (public.is_admin(auth.uid()));

-- Seed helper: after creating users in Supabase Auth, create profile rows:
-- insert into public.profiles (id, role, display_name, active) values ('<auth-user-uuid>', 'admin', 'Seu Nome', true);
-- insert into public.profiles (id, role, display_name, active) values ('<auth-user-uuid>', 'operador', 'Operador X', true);
-- insert into public.profiles (id, role, display_name, active) values ('<auth-user-uuid>', 'visualizador', 'Visualizador X', true);
